### ISSUE TITLE
Any reason why RenewAccessTokenIfNeeded() hides Exception?

### ISSUE THREAD

**Issue by Guacam-Ole** [OfficeDev/Product-List-Code-Sample#2]
i currently had a network-issue (proxy authentication) that caused a WebException in "RenewAccessTokenIfNeeded" (when debugging locally). That Error is really hard to find when its hidden.

As this Class comes with the standard VS-Template: Is there a reason for that behaviour? Shouldn't we throw the Exception?

**Comment by Rick-Kirkham** [comment]
Sorry for not responding to this earlier. I will research and report back here soon.

**Comment by Rick-Kirkham** [comment]
@OleAlbers 
Good catch. I think that is a design flaw in the method. As you noted, the method is in a file generated by the Office Tools for SharePoint. I will file a bug with the team that produces the tools.
